{  msg_downloaded_1 := 'Downloaded ';
   msg_downloaded_2 := ' bytes';
   msg_redirection_1 := 'Redirection to ';
   msg_redirection_2 := ' detected.';
   msg_redirection_3 := 'Follow redirection?';
   smdg_timeout := 'Time out'
   msg_callee_1 := 'Script contains arguments.callee.toString() function.';
   msg_callee_2 := 'Please referr to the tutorial on Malzilla''s website on how to replace this function',
   msg_replaceeval_1 := 'Script contains eval() function.';
   msg_replaceeval_2 := 'Replace with ';
   msg_replaceeval_3 := '() ?';
   msg_overrideeval_1 := 'Script contains eval() function.';
   msg_overrideeval_2 :='Override it?';
   smsg_compiled := 'Script compiled';
   smsg_notcompiled := 'Script can''t be compiled';
   msg_scriptcontainsscript := 'Compiled script is also a script';
   smsg_working := 'Working...';
   msg_newtab'New Tab';
   msg_oddbyte := 'Odd-byte file size, cannot be Unicode';
   smsg_stringnotfound := 'String not found';
   msg_noftp := 'Malzilla can''t handle FTP or HTTPS protocols';
   msg_cachecorr_1 := 'Cache is corrupted. Please save your files and clear the cache'
   smsg_itemsent := 'Item sent to Downloader tab';
   msg_urinotdetected := 'URI base (not detected):';
   msg_uridetected := 'URI base (detected):';
   msg_selection := 'Selection length: ';
   msg_selectdir_files := 'Select where to save files';
   msg_newversion := 'Newer version is available';
   msg_nonewversion := 'You have the newest version';
   msg_selectdirlog := 'Select where to save log';
   msg_folderoccupied := 'Please select another folder. This one already contains a log.';

    
    
//frmCacheList

    msg_cachecorr_2 := 'File is missing from the cache';
    msg_cachecorr_3 := 'Cache is corrupted';

//untDownloaderThread

    msg_canceled := 'Canceled';


//untJSBrowser

    msg_violation_1 := 'Some violation occured';
    msg_violation_2 := 'in SpiderMonkey engine';

untListDownloaderThread

    smsg_finished := 'Finished';

//untJSBrowserProxy
    smsg_preparing_temp := 'Preparing temp folder';
    //smsg_working := 'Working...';
    //smsg_script_compiled := 'Script compiled';
    smsg_collecting_garbage := 'Collecting garbage';
    smsg_script_evaluated := 'Script can''t be compiled, but it produced evaluation results';
    //smsg_script_not_compiled := 'Script can''t be compiled';
     }
